### ISSUE TITLE
Unable to access spreadsheet

### ISSUE THREAD

**Issue by Damo-ai** [SAP-samples/teched2021-ISP160#3]
Hi,

The link does not work now. Any alternative link for the same?
https://sap-my.sharepoint.com/:x:/p/aliza_zeldin/EUD9VtKQflBKncwEtu2KuQsBV1c39jz9ivl3VHkGwy9yFw?e=KA3t9F
Regards
Damo

**Comment by iBaryo** [comment]
hi @Damo-ai -
the test credentials originally provided were disabled now - i suggest you reach out to SAP support in order to get a hold of a SAP test tenant you can run the workshop on.
